//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coink.BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coink.BLL.Properties.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception occurred in sending the arguments..
        /// </summary>
        internal static string ERROR_ARGUMENT {
            get {
                return ResourceManager.GetString("ERROR_ARGUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database error..
        /// </summary>
        internal static string ERROR_DATABASE {
            get {
                return ResourceManager.GetString("ERROR_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception occurred in the application code..
        /// </summary>
        internal static string ERROR_EXCEPTION {
            get {
                return ResourceManager.GetString("ERROR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data not found..
        /// </summary>
        internal static string ERROR_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errors were found in the input parameters..
        /// </summary>
        internal static string ERROR_NULLREFERENCE {
            get {
                return ResourceManager.GetString("ERROR_NULLREFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se encontraron errores en los parametros de entrada..
        /// </summary>
        internal static string ERROR_PARAMS {
            get {
                return ResourceManager.GetString("ERROR_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time Out exception when executing the operation..
        /// </summary>
        internal static string ERROR_TIMEOUT {
            get {
                return ResourceManager.GetString("ERROR_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query done correctly..
        /// </summary>
        internal static string MESSAGE_SUCCESS {
            get {
                return ResourceManager.GetString("MESSAGE_SUCCESS", resourceCulture);
            }
        }
    }
}
